# Generated by Django 4.0.2 on 2022-08-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_folowercount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folowercount',
            old_name='username',
            new_name='follower',
        ),
    ]
